//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroPost.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostId { get; set; }
        public Nullable<bool> IsPublicPost { get; set; }
        public Nullable<int> UserId { get; set; }
        public string PostText { get; set; }
    
        public virtual User User { get; set; }
    }
}
